### ISSUE TITLE
БАГ! При создании точки в маршруте 

### ISSUE THREAD

**Issue by galievruslan** [galievruslan/mss-mobile#7]
При создании точки в маршруте, после выбора клиента и точки отгрузки, после нажатия на кнопку ОК вышла ошибка:
799000 2013-05-15 08:55:02,000 [785421882] [ERROR] - System.Net.WebException: An error message cannot be displayed because an optional resource assembly containing it cannot be found ---> System.Net.Sockets.SocketException: An error message cannot be displayed because an optional resource assembly containing it cannot be found
at System.Net.HttpWebRequest.fillBuffer()
at System.Net.HttpWebRequest.getLine()
at System.Net.HttpWebRequest.parseResponse()
at System.Net.HttpWebRequest.startReceiving()
at System.Net.Connection.startReceiving()
at WorkItem.doWork()
at System.Threading.Timer.ring()

at System.Net.HttpWebRequest.finishGetResponse()
at System.Net.HttpWebRequest.GetResponse()
at MSS.WinMobile.Infrastructure.Web.Repositories.Utilites.RequestDispatcher.Dispatch()
at MSS.WinMobile.Infrastructure.Web.Repositories.WebConnection.Get()
at MSS.WinMobile.Infrastructure.Web.Repositories.WebQueryObject`1.Execute()
at MSS.WinMobile.Infrastructure.Web.Repositories.WebQueryObject`1.GetEnumerator()
at System.Collections.Generic.List`1..ctor()
at System.Linq.Enumerable.ToList()
at System.Linq.Enumerable.ToArray()
at MSS.WinMobile.Synchronizer.SynchronizationCommand`2.Execute()
at MSS.WinMobile.Synchronizer.FaultHandling.RepeatOnErrorCommand`2.Execute()
at MSS.WinMobile.UI.Presenters.Presenters.SynchronizationPresenter.RunSynchronizationInBackground()

799000 2013-05-15 08:55:02,000 [785421882] [ERROR] - Excecution try #1 failed
System.Net.WebException: An error message cannot be displayed because an optional resource assembly containing it cannot be found ---> System.Net.Sockets.SocketException: An error message cannot be displayed because an optional resource assembly containing it cannot be found
at System.Net.HttpWebRequest.fillBuffer()
at System.Net.HttpWebRequest.getLine()
at System.Net.HttpWebRequest.parseResponse()
at System.Net.HttpWebRequest.startReceiving()
at System.Net.Connection.startReceiving()
at WorkItem.doWork()
at System.Threading.Timer.ring()

at System.Net.HttpWebRequest.finishGetResponse()
at System.Net.HttpWebRequest.GetResponse()
at MSS.WinMobile.Infrastructure.Web.Repositories.Utilites.RequestDispatcher.Dispatch()
at MSS.WinMobile.Infrastructure.Web.Repositories.WebConnection.Get()
at MSS.WinMobile.Infrastructure.Web.Repositories.WebQueryObject`1.Execute()
at MSS.WinMobile.Infrastructure.Web.Repositories.WebQueryObject`1.GetEnumerator()
at System.Collections.Generic.List`1..ctor()
at System.Linq.Enumerable.ToList()
at System.Linq.Enumerable.ToArray()
at MSS.WinMobile.Synchronizer.SynchronizationCommand`2.Execute()
at MSS.WinMobile.Synchronizer.FaultHandling.RepeatOnErrorCommand`2.Execute()
at MSS.WinMobile.UI.Presenters.Presenters.SynchronizationPresenter.RunSynchronizationInBackground()

**Comment by golfarid** [comment]
Synchronization thread killing bug. Fixed.
